export const STRINGS = {
  'key.enter':        'ENTER',
  'key.swap':         'SWAP',
  'key.rot':          'ROT',
  'key.clx':          'CLX',
  'key.clr':          'CLR',
  'key.clr_confirm':  'Sure?',
  'key.undo':         'UNDO',
  'key.sqrt':         '√',
  'key.pow':          'yˣ',
  'key.pct':          '%',
  'key.sign':         '±',
  'error.underflow':  'Error: Stack underflow',
  'error.div_zero':   'Error: ÷ 0',
  'error.sqrt_neg':   'Error: √ <0',
  'error.overflow':   'Error: Overflow',
  'error.generic':    'Error',
  'error.crash':      'Something went wrong. Tap to restart.',
  'display.empty_history': 'No calculations yet.',
  'display.history_title': 'History',
  'display.sig_label':     'SIG',
  'landscape.message':     'Rotate your device to use Stax.',
  'meta.app_name':         'Stax',
  'meta.description':      'The RPN calculator with taste.',
};
