export const STRINGS = {
  'key.enter':        'ENTER',
  'key.swap':         'SWAP',
  'key.rot':          'ROT',
  'key.clx':          'CLX',
  'key.clr':          'CLR',
  'key.clr_confirm':  'Sure?',
  'key.undo':         'UNDO',
  'key.copy':         'COPY',
  'key.copy_success': '\u2713 Copied',
  'key.copy_fail':    'Failed',
  'key.sqrt':         '\u221A',
  'key.pow':          'y\u02E3',
  'key.pct':          '%',
  'key.sign':         '\u00B1',
  'key.inv':          '1/x',
  'error.underflow':  'Error: Stack underflow',
  'error.div_zero':   'Error: \u00F7 0',
  'error.sqrt_neg':   'Error: \u221A <0',
  'error.overflow':   'Error: Overflow',
  'error.generic':    'Error',
  'error.crash':      'Something went wrong. Tap to restart.',
  'display.empty_history': 'No calculations yet.',
  'display.history_title': 'History',
  'display.sig_label':     'SIG',
  'landscape.message':     'Rotate your device to use Stax.',
  'meta.app_name':         'Stax',
  'meta.description':      'The RPN calculator with taste.',
};
